### PR TITLE
ast.Index should visit target and key

### LINKED ISSUE #28: Cannot evaluate arithmetic inside of array index
Trying to evaluate something like `${foo[2-1]}`, where `foo` is just an array with at least two members, fails with (formatting mine):

    Error: node doesn't support evaluation: *ast.Arithmetic{
        Op:2, Exprs:[]ast.Node{
            *ast.LiteralNode{
                Value:2,
                Typex:0x8,
                Posx:ast.Pos{Column:7, Line:1}
            },
            *ast.LiteralNode{
                Value:1, 
                Typex:0x8, 
                Posx:ast.Pos{Column:9, Line:1}
            }
        },
        Posx:ast.Pos{Column:7, Line:1}
    }

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #28 

This fixes #28 but is also a general refactor, so the scope is a bit larger. 

The visitor pattern shouldn't discriminate what values are and are not
visited. This allows us to use the type checking stack and the eval
stack more properly and avoid evaling multiple nodes within the index
eval.

In turn, this enables all eval operations to work in both targets and
keys (fixes #28). We still enforce that the list target be a variable
access, however.

This also removes some type checking from eval since those type errors should be caught in the type checker itself and we should assume types are correct by the time they reach the evaluation step.

### CODE REVIEW

File: ast/index.go [hunk 1]
```diff
@@ -13,11 +13,8 @@ type Index struct {
 }
 
 func (n *Index) Accept(v Visitor) Node {
-	// the Key may have further interpolations
-	switch n.Key.(type) {
-	case *Call, *VariableAccess:
```
Comment (maxenglander) [inline ast/index.go]: So my understanding is that dropping this conditional check allows keys that are arithmetic nodes to get pushed onto the type checking stack, which then get transformed into call nodes, which then get evaluated? Whereas, previously, index keys that were arithmetic nodes would be let un-type-checked, and could not be handled at the type-checking phase.

Comment (maxenglander) [inline ast/index.go]: Ah I see - by changing to use `key := stack.Pop()` eval phase can now get access to the result of the call node evaluation.
